# 부대별 병력 수 표준 스케일링 적용하기

모든 사단은 사단별로 다른 업무를 맡고 있는 5개의 부대(troop1, troop2, troop3, troop4, troop5)로 나누어 운영을 하고 있습니다. 전체를 관장하는 참모장으로 전체적으로 봤을 때 부대별 규모를 좀 더 잘 비교하기 위해 표준 스케일링을 하고자 합니다. troop1부터 troop5까지 다섯 개의 필드로 구성되어 있는 데이터셋을 읽어 표준 스케일링(Standard Scaling)을 적용해 보는 것이 여러분이 해야 할 일입니다.

## 데이터 셋 설명

'military_scaling_dataset.csv'

이 파일에는 사단별(id)로 5개의 부대 병력수가 존재합니다. 아래 표는 헤더를 포함하여 처음 6개의 레코드를 나타냅니다.

| id | troop1 | troop2 | troop3 | troop4 | troop5 |
| --- | --- | --- | --- | --- | --- |
| 0 | 3436 | 418 | 3730 | 457 | 2504 |
| 1 | 3487 | 1470 | 220 | 2565 | 4468 |
| 2 | 151 | 1937 | 1589 | 1317 | 4549 |
| 3 | 2043 | 1373 | 1693 | 2175 | 2284 |
| 4 | 607 | 4393 | 2707 | 3188 | 2825 |

## 문제 설명

주어진 데이터는 헤더를 포함하여 101개의 레코드로 구성되어 있습니다. 필드별로 표준 스케일링을 적용해서 그 결과를 submission.csv 파일로 저장하는 것이 목표입니다. 표준 스케일링은 평균을 0, 표준편차를 1로 만드는 것을 말합니다. 다음과 같은 과정을 거치게 됩니다.

 1. 먼저 부대별(troop1부터 troop5 별로)로 평균(μ)과 표준편차(σ)를 구합니다.
 2. 해당 부대 컬럼 데이터 포인트에서 평균(μ)을 빼고 표준편차(σ)로 나눕니다.

결과적으로 모든 특성들이 같은 스케일을 가지게 되어, 서로 다른 단위나 범위를 가진 특성들을 비교하거나 머신러닝 알고리즘에 적용할 때 유용합니다. 이를 위해 직접 계산해도 되지만 Scikit-learn의 StandardScaler를 사용하는 것을 추천합니다.


### 초기코드 선택(Python)

In [1]:
#from google.colab import drive
#drive.mount('/content/drive')

In [2]:
# 초기코드 - python
import pandas as pd

# 데이터 로드
data_log = pd.read_csv('./data/military_scaling_dataset.csv')

data_log.head()

   id  troop1  troop2  troop3  troop4  troop5
0   0    3436     418    3730     457    2504
1   1    3487    1470     220    2565    4468
2   2     151    1937    1589    1317    4549
3   3    2043    1373    1693    2175    2284
4   4     607    4393    2707    3188    2825

### 최종 제출 파일

예를 들어 최종 제출 파일의 처음 5개(헤더 제외)의 레코드를 보면 다음과 같은 형태가 되어야 합니다. 앞서 입력 파일 순서대로 들어와야 합니다.

| troop1 | troop2 | troop3 | troop4 | troop5 |
| --- | --- | --- | --- | --- |
| 1.27 | 1.45 | 0.10  | -0.81 | 1.41  |
| -1.66 | -1.24 | 0.87  | -0.69 | 0.06  |
| -0.68 | -0.81 | 0.55  | -0.07 | -1.52 |
| 0.39 | 0.53  | -1.24 | -1.01 | 0.99  |
| 1.27  | 1.45  | 0.10  | -0.81 | 1.41  |

In [3]:
# 여기에 코드를 작성하세요.
from sklearn.preprocessing import StandardScaler

troop_cols = ['troop1', 'troop2', 'troop3', 'troop4', 'troop5']

# id는 제외하고 troop 컬럼만 표준 스케일링 (모집단 표준편차, ddof=0)
scaler = StandardScaler()
scaled = scaler.fit_transform(data_log[troop_cols])

df = pd.DataFrame(scaled, columns=troop_cols)

# 검증: 평균 ≈ 0, 표준편차 ≈ 1
print(df.mean().round(6).to_dict())
print(df.std(ddof=0).round(6).to_dict())
df.head()

{'troop1': -0.0, 'troop2': 0.0, 'troop3': 0.0, 'troop4': 0.0, 'troop5': 0.0}
{'troop1': 1.0, 'troop2': 1.0, 'troop3': 1.0, 'troop4': 1.0, 'troop5': 1.0}

     troop1    troop2    troop3    troop4    troop5
0  0.603383 -1.581970  0.803209 -1.687678  0.031074
1  0.641106 -0.826250 -1.613627 -0.146273  1.454984
2 -1.826420 -0.490773 -0.670992 -1.058832  1.513709
3 -0.426972 -0.895931 -0.599382 -0.431447 -0.128427
4 -1.489133  1.273533  0.098815  0.309276  0.263800

### 결과 저장

채점을 위해, 위에서 구한 데이터를 현재 파일과 같은 디렉토리(.ipynb 파일이 있는 디렉토리)에 `submission.csv`이라는 이름으로 저장해주세요.

In [4]:
# 여기에 코드를 작성하세요.
df.to_csv('submission.csv')

In [6]:
# csv 파일 저장 예시 - python
pd.read_csv('submission.csv').head()

   Unnamed: 0    troop1    troop2    troop3    troop4    troop5
0           0  0.603383 -1.581970  0.803209 -1.687678  0.031074
1           1  0.641106 -0.826250 -1.613627 -0.146273  1.454984
2           2 -1.826420 -0.490773 -0.670992 -1.058832  1.513709
3           3 -0.426972 -0.895931 -0.599382 -0.431447 -0.128427
4           4 -1.489133  1.273533  0.098815  0.309276  0.263800